import js from "@eslint/js";
import prettier from "eslint-config-prettier";

export default [
    js.configs.recommended,
    prettier,
    {
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "module",
            globals: {
                // Browser globals
                window: "readonly",
                document: "readonly",
                navigator: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                fetch: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                FormData: "readonly",
                Blob: "readonly",
                File: "readonly",
                FileReader: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                CustomEvent: "readonly",
                Event: "readonly",
                HTMLElement: "readonly",
                Element: "readonly",
                Node: "readonly",
                NodeList: "readonly",
                MutationObserver: "readonly",
                IntersectionObserver: "readonly",
                ResizeObserver: "readonly",
            },
        },
        rules: {
            "prefer-template": "off",
            "no-var": "warn",
            "no-unused-vars": "warn",
            "camelcase": "warn",
            "no-nested-ternary": "warn",
            "no-console": "warn",
            "no-template-curly-in-string": "warn",
            "no-self-compare": "warn",
            "arrow-body-style": "warn",
        },
    },
    {
        ignores: [
            "**/*.min.js",
            "**/dist/**",
            "**/vendor/**",
            ".cache/**",
            ".idea/**",
            ".vscode/**",
            "node_modules/**",
            "coverage/**",
            "webpack.*",
            "vite.config.js",
        ],
    },
];
